version: '3.8'

services:
  api:
    build: 
      context: ..
      dockerfile: deploy/Dockerfile
      target: api
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - STORAGE_TYPE=redis
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - ../:/app
    restart: unless-stopped

  streamlit:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
      target: streamlit
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - STORAGE_TYPE=redis
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - api
    volumes:
      - ../:/app
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  vector-mock:
    image: milvusdb/milvus:v2.3.3-latest
    ports:
      - "19530:19530"
      - "9091:9091"
    environment:
      - ETCD_ENDPOINTS=etcd:2379
      - MINIO_ADDRESS=minio:9000
    volumes:
      - milvus_data:/var/lib/milvus
    restart: unless-stopped
    depends_on:
      - etcd
      - minio

  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - etcd_data:/etcd
    restart: unless-stopped
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd

  minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    volumes:
      - minio_data:/minio_data
    restart: unless-stopped
    command: minio server /minio_data

volumes:
  redis_data:
  milvus_data:
  etcd_data:
  minio_data: 