name: End-to-End Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-test:
    name: End-to-End Tests
    runs-on: ubuntu-latest
    
    # Skip running on external PRs that don't have access to secrets
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev,redis]"
    
    - name: Build and start services
      run: |
        docker-compose -f deploy/docker-compose.yml up -d
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    
    - name: Wait for services to be ready
      run: |
        sleep 10  # Add appropriate wait time or health check
    
    - name: Run e2e tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        REDIS_HOST: localhost
        REDIS_PORT: 6379
      run: pytest -xvs tests/integration --marker="e2e"
    
    - name: Cleanup
      if: always()
      run: |
        docker-compose -f deploy/docker-compose.yml down
